name: szadejkompas
description: Szadejkompas — offline nawigacja GPS dla E. Szadejko.
publish_to: 'none'
version: 3.0.0+5

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^13.0.2
  flutter_compass: ^0.8.1
  shared_preferences: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: false
  image_path: ikona-szadejkompas2.png
  adaptive_icon_background: "#12141C"
  adaptive_icon_foreground: ikona-szadejkompas2.png

flutter:
  uses-material-design: true
  assets:
    - ikona-szadejkompas2.png
